### ISSUE TITLE
How to install this app ?

### ISSUE THREAD

**Issue by gagantous** [wraithseeker/Visualnoveler_Old#3]
Could you please make a tutorial of how to install this web on windows ?
i have install 'ruby on rails' package 
i have used `bundle install` on cmd ut its got and error like kgio or kind like that.
i got the solution of how to solve kgio package issue.
but i still cannot install this web app ..
please help 
( and sorry i am new on this programming language ( ruby ) and this is the first time i use ruby on rails framework rails. I usually  used codeigniter )
thanks

**Comment by wraithseeker** [comment]
It's far too complicated to setup this app (which is no longer maintained since the website is down).
